M48
; DRILL file {KiCad 8.0.6} date 2025-03-28T19:02:09-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-28T19:02:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X5.274Y-1.921
X5.274Y-3.8502
X7.5575Y-1.921
X7.5575Y-3.8502
M30
